### PR TITLE
Added Kharagpur Winter of Code To list.

### PR DESCRIPTION
**Pull request by divyanshu-rawat**
Kharagpur Winter of Code is a 5-week long online program
for the students of IIT Kharagpur, who are new to open source software development. The program will not only help students to get involved in open source, but will also prep them for many open source summer programs, Google Summer of Code being one of them.

### CODE REVIEW

**Comment by ayushi-jha** [comment]
Is this program available to students outside IIT Kharagpur?

**Comment by divyanshu-rawat** [comment]
If you are not a student of IIT Kharagpur and yet have come to know about KWoC,
then sure you can apply ! 
Even I am working on a project in it and I am not from IIT Kharagpur.

**Comment by tapasweni-pathak** [comment]
The about page says "Kharagpur Winter of Code is a 5-week long online program for the students of IIT Kharagpur, who are new to open source software development".

I want this list to have programs which covers a broad category of students who are eligible to participate.

Thank you!

**Comment by divyanshu-rawat** [comment]
@tapasweni please read FAQ on the mentioned link http://kwoc.kossiitkgp.in/resources/faq#s2 
it says  If you are not a student of IIT Kharagpur and yet have come to know about KWoC, then sure you can apply ! Although our aim of the program is to close monitor the students of the campus.
And the fact is that Even I am not from IIT Kharagpur  and I am working on a project it and many of my friends too.

**Pull request closed without merging**
