### PR TITLE
Added open mainframe project

### PR DESCRIPTION
**Pull request by palash25**
Closes: #28

### CODE REVIEW

**Comment by tapasweni-pathak** [comment]
Happy how this list is being used, thank you for sharing this! Can you give a shout out on the Slack channel?

**Comment by palash25** [comment]
You mean the OSHC slack channel?

**Comment by tapasweni-pathak** [comment]
Yeah, are you part of it? otherwise I'll do from main account, let me know.

**Comment by palash25** [comment]
No I can do it.

**Pull request merged**
